### PR TITLE
Allow video/mp4 in content_type checking, resolves #6

### LINKED ISSUE #6: Add support for mp4 videos
Based on Speechmatics FAQs, mp4 videos are supported:
https://speechmatics.com/support

I tested this and they were able to transcribe mp4 videos. Attaching mp4 videos when creating jobs will fail since the content type does not match the allowed types in the "attach_audio" method:

https://github.com/PRX/speechmatics/blob/a0c272fb32e6405af63546a24b4c9134bb77d957/lib/speechmatics/user/jobs.rb#L32

Pull request incoming :)

### PR DESCRIPTION
**Pull request by marvs**
I was not able to add tests for this change since we need a zero-length mp4 file for this, and I cannot find a sample mp4 file that we can use.

### CODE REVIEW

**Comment by kookster** [comment]
Try this one?

[blank.mp4 | uploaded via ZenHub](https://files.zenhub.io/55d5e006aed2167110cc52c9)

**Comment by kookster** [comment]
Thanks for the PR!

I think, upon rereading the SM support page, that probably the right validation is to make sure this is an 'audio' or a 'video' mime type file rather than just mp4.

Currently, the SM gem only checks for audio, which is wrong. My guess is SM uses ffmpeg to extract the audio to a standard format at some point in the automated processing, so probably best to just check for audio and video, as ffmpeg can pull audio out of practically any type of video file.

**Comment by marvs** [comment]
You are right, I may have misinterpreted that. Re-reading the FAQs it says 
"We support almost all file types, including aac, aif, m4a, mov, mp3, mp4, wav and more!"
So they should support majority of audio and video formats :)

So should I update the PR and add in the sample mp4/test and the content type check or do you want to handle it from here?

Thanks!

**Comment by kookster** [comment]
I'd prefer if you made the change to the PR, but I may get to it eventually if you cannot.

(I'm not actively using this gem anymore, and I never used it for video, so its not high  on my list.)

**Comment by marvs** [comment]
Hello Andrew, I pushed the new commit to this PR, this includes the changes to checking audio and video files, as well as including the blank mp4 test file with tests. Thanks!

**Comment by kookster** [comment]
great work, thanks!

**Comment by kookster** [comment]
@marvs I just released 0.1.4 with this fix in the gem.

**Pull request merged**
